# Generated by Django 3.0.7 on 2020-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
